import { Inter, Fira_Code as FontMono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import AppProvider from "./appProvider";
import Navigation from "./navigation";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const fontMono = FontMono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata = {
  title: {
    default: "Chee-Tah",
    template: `%s - HeyGen Streaming Avatar SDK Demo`,
  },
  description: "Generated by create next app",
  icons: {
    icon: "/heygen-logo.png",
  },
};

export const viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${inter.variable} ${fontMono.variable} font-sans`}
    >
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{metadata.title.default}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href={metadata.icons.icon} />
      </head>
      <body className={inter.className}>
        <AppProvider>
          <Navigation />
          <Providers themeProps={{ attribute: "class", defaultTheme: "light" }}>
            {children}
          </Providers>
        </AppProvider>
      </body>
    </html>
  );
}
